name = "spinogambinobet-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinobet.com.pt"
HMAC_KEY = "927ef93e0a5138f95068bf45dd73ff2890735527caa3c021b94a3f0e989e2dba"
COOKIE_NAME = "zeb"
PLAY_PATH = "start"
BUTTON_ID = "p083a5432c44662155bddfd779644c000"
GATE_SALT = "7f783c4d1efa4cd4"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "417h"
CTA_SELECTOR = ".play-button"
