name = "spinogambinobet-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinobet.com.pt"
HMAC_KEY = "927ef93e0a5138f95068bf45dd73ff2890735527caa3c021b94a3f0e989e2dba"
COOKIE_NAME = "2yz"
PLAY_PATH = "launch"
BUTTON_ID = "p083a5432c44662155bddfd779644c000"
GATE_SALT = "1f154dcbefea2bef"
